### ISSUE TITLE
waiting for others team members to provide their github account

### ISSUE THREAD

**Issue by kasparov112000** [kasparov112000/biolinkdepot#1]

**Comment by jgrosvenCS178** [comment]
I think thats everyone

**Comment by jgrosvenCS178** [comment]
oh wait. not everyone

**Comment by kasparov112000** [comment]
I am just testing github capabilities, but you can do project management from start to end, etc...what I said in class

**Comment by jgrosvenCS178** [comment]
yeah me too. i needed a refresh on git. thats why i pull request and contribute to issues

**Comment by kasparov112000** [comment]
Seems we are all in
